spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${BD_USER
    password: ${DB_PASSWORD
    name: ${DB_NAME}