name: TestCheck+Deploy

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - run: ./gradlew --version
      - run: ./gradlew check

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - run: ./gradlew test

  build:
    needs: [test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle
      - run: ./gradlew clean build -x test
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: backend_jar
          path: backend/build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend_jar
          path: jar

      - name: Upload jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "jar/*.jar"
          target: "~/app"

      - name: Start app
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            mkdir -p ~/app
            cd ~/app
            # берём самый свежий jar, который только что загрузили
            JAR=$(ls -t *.jar | head -n1)

            # останавливаем то, что слушает 8080 (lsof -> fuser fallback)
            if command -v lsof >/dev/null 2>&1; then
              PID=$(lsof -t -i:8080 || true)
              if [ -n "$PID" ]; then kill -9 "$PID" || true; fi
            else
              fuser -k 8080/tcp || true
            fi

            nohup java -jar "$JAR" > app.log 2>&1 &
            echo "Started $JAR"
