name: FrontCheck
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linter
        run: npm install && npm run lint
        working-directory: frontend
  format:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run formatter
        run: npm install && npm run format
        working-directory: frontend
